#!/bin/bash

cd /etc

#Test to see if host is Arch based
if [ -d /etc/pacman.d ]
then
	sudo pacman -syu
fi

#Test to see if host is Debian based
if [ -d /etc/apt ]
then
	sudo apt-get update && sudo apt-get dist-upgrade -y
fi
