#!/bin/bash

echo "What is your favorite color?"

echo "1 - Red"
echo "2 - Orange"
echo "3 - Yellow"
echo "4 - Green"
echo "5 - Blue"
echo "6 - Indigo"
echo "7 - Violet"

read favColor;

case $favColor in
	1) echo "Red";;
	2) echo "Orange";;
	3) echo "Yellow";;
	4) echo "Green";;
	5) echo "Blue";;
	6) echo "Indigo";;
	7) echo "Violet";;
	*) echo "That wasn't a valid option...";; #Asterik is default case
esac
